version: '2'
services:
  webserver:
    depends_on:
      - dbserver
    image: phpstorm/php-71-apache-xdebug-26
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PMA_HOST: dbserver
    links:
      - dbserver

  dbserver:
    image: mysql:5.7
    volumes:
      - ./:/var/lib/mysql2
    ports:
      - "3306:3309"
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: admin
        MYSQL_USER: abcd
        MYSQL_PASSWORD: abcd

  app:
    depends_on:
      - dbserver
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: dbserver